# Generated by Django 4.2.13 on 2024-07-08 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_post_excerpt_post_updated_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
    ]
